[build]
publish = "web/dist"
command = "bun run build"

[[redirects]]
from = "/api/*"
to = "https://hubapi.chenify.top/api/:splat"
status = 200
force = true
headers = { "Host" = "hubapi.chenify.top", "Access-Control-Allow-Origin" = "*", "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS", "Access-Control-Allow-Headers" = "Content-Type, Authorization" }

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
